import processGlossary from '../_helpers/process-glossary';
import sortByObjectKey from '../_helpers/sort-by-object-key';

export async function get(req, res, next) {
	let glossaryRaw = [
        {
          "category": "Co-op type",
          "term": "Consumer co-op",
          "glossaryDefinition": "Consumer co-ops are co-ops that are owned by the consumers.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Cooperative",
          "glossaryDefinition": "Cooperatives, or co-ops, are organizations and businesses where members have decision-making power - versus in traditional businesses, where decisions are typically made by shareholders and investors. Members of a cooperative often come together based on a shared goal - economic, social, environmental, or cultural.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "Coop",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Credit union",
          "glossaryDefinition": "Credit unions are co-ops that provide traditional banking services, but are owned by the people who bank there.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Data",
          "glossaryDefinition": "Data co-ops are a broad category covering co-ops that run on protocols or distributed ledgers, co-ops that help other co-ops exchange data, co-ops that provide internet infrastructure, or data trusts.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Housing",
          "glossaryDefinition": "Housing co-ops are co-ops that supply housing for its members, and can be both for-profit and non-profit. Housing costs are determined by the collective costs of the co-op, and shared equitably among members. (Co-op Creator)",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Multi-stakeholder",
          "glossaryDefinition": "Multi-stakeholder co-ops are co-ops that are formed and owned by two or more stakeholder groups. These groups can include workers, consumers, producers, and more.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Platform",
          "glossaryDefinition": "Platform co-ops are co-ops that use a website, mobile app, or protocol to sell goods or services. The co-op and the platform are owned by workers and users.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Producer",
          "glossaryDefinition": "Producer co-ops (also known as marketing co-ops) is made up of people who generally are in the same sector or conduct the same type of business. They come together to do collective marketing.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Purchasing",
          "glossaryDefinition": "Purchasing co-ops are groups or businesses that come together to purchase services or supplies and lower operational costs.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Social",
          "glossaryDefinition": "Social co-ops are created to provide social services; its goal is to provide benefit to the community.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Co-op type",
          "term": "Worker",
          "glossaryDefinition": "Worker co-ops are co-ops that are owned and run by the workers. Not every employee has to be an owner.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Stages of development",
          "term": "Development",
          "glossaryDefinition": "When a co-op begins to develop their organization beyond an idea: Member structure is defined, recruitment has been planned, ideas are turned into a prototype and selling mechanisms are being developed and tested. Usually at this point there are initial investors are involved.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Stages of development",
          "term": "Expansion",
          "glossaryDefinition": "When a co-op is comfortable and can begin thinking about expanding to have financial reserves and dividends, pursuing franchising opportunities, and more.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Stages of development",
          "term": "Ideation",
          "glossaryDefinition": "When a co-op is testing their business model to make sure their idea works, and starting to recruit founding members.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Stages of development",
          "term": "Operational",
          "glossaryDefinition": "When a co-op becomes operational: First paying clients or members using the platform, some income coming in. Potentially some secondary capital with investor members.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Stages of development",
          "term": "Stability",
          "glossaryDefinition": "When a co-op breaks even financially: Regular clients are established, cash flow stabilized and covering fixed costs, and growing into new customer segments.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tech term",
          "term": "Free software",
          "glossaryDefinition": "Free software is software where anyone can freely view the source code, modify it, and redistribute it. Contrary to the name, free software is not necessarily free of cost.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tech term",
          "term": "Open source software",
          "glossaryDefinition": "Open source software is software with source code that anyone can view and change. Open source software can be both paid and for free.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tech term",
          "term": "Proprietary software",
          "glossaryDefinition": "Proprietary software is software that only the original authors can view and modify. Proprietary software can be both paid and for free.",
          "toolExplanation": "n/a - no tool explanation needed",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Accounting",
          "glossaryDefinition": "Accounting is the process of keeping financial accounts and records. This can include recording, measuring, and communicating your finances.",
          "toolExplanation": "Accounting tools help you keep track of your financial accounts and records.",
          "Synonym": "bookkeeping",
          "Synonym__1": "balancing the books",
          "Synonym__2": "taxes",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Bulk email",
          "glossaryDefinition": null,
          "toolExplanation": "Bulk email tools help you send out emails to a large amount of people quickly and efficiently.",
          "Synonym": "Emailing",
          "Synonym__1": "Mass email",
          "Synonym__2": "Email blast",
          "Synonym__3": "Marketing emails",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Coding",
          "glossaryDefinition": "Coding is used to create websites, apps, and other technologies that we interact with.",
          "toolExplanation": "Coding tools give you a way to write the code that builds your technology.",
          "Synonym": "Programming",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Collaboration",
          "glossaryDefinition": null,
          "toolExplanation": "Collaboration tools help you and your team members work together on a specific thing more effectively.",
          "Synonym": "Working together",
          "Synonym__1": "Remote working",
          "Synonym__2": "Remote collaboration",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Communication",
          "glossaryDefinition": "Communication is the process of sharing or exchanging information with other people",
          "toolExplanation": "Communication tools give you a way to talk and write to others.",
          "Synonym": "Talking",
          "Synonym__1": "Connect",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Crowdfunding",
          "glossaryDefinition": "Crowdfunding is raising funds for a project or organization, typically through small donations from a large amount of people. This often happens through the internet.",
          "toolExplanation": "Crowdfunding tools help you raise money for your co-op or project online.",
          "Synonym": "Fundraising",
          "Synonym__1": "Campaign",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Customer relationship management",
          "glossaryDefinition": "Customer relationship management is a type of software used to manage your organization's relationships with current and prospective customers. This usually looks like keeping track of your customer's contact information, seeing their previous transactions with you, and integrating with other related apps such as billing and payments.",
          "toolExplanation": "Customer relationship management tools give you a way to keep track of your customers, store their contact information, and see how they've interacted with you in the past. Certain CRM tools also allow you integrate other tools, like billing and payments.",
          "Synonym": "CRM",
          "Synonym__1": "Customer relation",
          "Synonym__2": "Customer retention",
          "Synonym__3": "Customer data",
          "Synonym__4": "Customer database",
          "Synonym__5": "Dashboard",
          "Synonym__6": "Customer management",
          "Synonym__7": "Sales",
          "Synonym__8": "Member management",
          "": "Dues planning",
          "__1": "Member outreach"
        },
        {
          "category": "Tool",
          "term": "Decision making",
          "glossaryDefinition": "Decision making is the process and action of making decisions.",
          "toolExplanation": "Decision making tools can help your co-op make decisions together through an online software.",
          "Synonym": "Governance",
          "Synonym__1": "Voting",
          "Synonym__2": "Sociocracy",
          "Synonym__3": "Polling",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Design",
          "glossaryDefinition": "Design is the process that is used to plan and define the functionality, appearance, and qualities of a certain thing. Designs are usually expressed visually, through drawings or diagrams.",
          "toolExplanation": "Design tools give you a way of visualizing your designs.",
          "Synonym": "UX",
          "Synonym__1": "UI",
          "Synonym__2": "User experience",
          "Synonym__3": "User interface",
          "Synonym__4": "Service design",
          "Synonym__5": "Visual design",
          "Synonym__6": "Graphic design",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Document editing",
          "glossaryDefinition": null,
          "toolExplanation": "Document editing tools allow you to write and edit. Some tools allow you to edit collaboratively with others in real time.",
          "Synonym": "Word procesing",
          "Synonym__1": "Text editor",
          "Synonym__2": "Note taking",
          "Synonym__3": "Note",
          "Synonym__4": "Live text editor",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Document sharing and storage",
          "glossaryDefinition": null,
          "toolExplanation": "Document storage tools allow you to store your documents and files in a cloud storage solution.",
          "Synonym": "Cloud storage",
          "Synonym__1": "File hosting",
          "Synonym__2": "Storage",
          "Synonym__3": "File storage",
          "Synonym__4": "Database",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Expense tracking",
          "glossaryDefinition": null,
          "toolExplanation": "Expense tracking tools give you a way to track all of your expenses. Some tools will allow you to add your budget, record income, and more.",
          "Synonym": "Spendings",
          "Synonym__1": "Tracking spendings",
          "Synonym__2": "Expense tally",
          "Synonym__3": "Budgeting",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Finances",
          "glossaryDefinition": "Finances is anything to do with the exchange or management of money",
          "toolExplanation": "Finance tools will help you manage your co-op's money.",
          "Synonym": "",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Group chat",
          "glossaryDefinition": null,
          "toolExplanation": "Group chat tools help you form a group and chat with them.",
          "Synonym": "Chatting",
          "Synonym__1": "Chat",
          "Synonym__2": "Messaging",
          "Synonym__3": "Group messaging",
          "Synonym__4": "Meetings",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Individual email",
          "glossaryDefinition": null,
          "toolExplanation": "Individual email tools help you set up an email account that you can send and receive emails at.",
          "Synonym": "Emailing",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Marketing",
          "glossaryDefinition": "Marketing is the process of determining how to interest potential customers and clients for your product or service, and then selling or distributing to them.",
          "toolExplanation": "Marketing tools help you sell or distribute your products or services to your customers.",
          "Synonym": "Selling",
          "Synonym__1": "Sales",
          "Synonym__2": "Retail",
          "Synonym__3": "Purchasing",
          "Synonym__4": "Commerce",
          "Synonym__5": "Marketplace",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Payment from customers",
          "glossaryDefinition": null,
          "toolExplanation": "These tools help you receive payment from your customers.",
          "Synonym": "Ecommerce",
          "Synonym__1": "POS",
          "Synonym__2": "Point of sale",
          "Synonym__3": "Shop online",
          "Synonym__4": "Cash register",
          "Synonym__5": "Invoicing",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Payment to vendors & suppliers",
          "glossaryDefinition": null,
          "toolExplanation": "These tools help you pay your vendors and suppliers.",
          "Synonym": "Accounts payable",
          "Synonym__1": "Invoicing",
          "Synonym__2": "Billing",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Payroll",
          "glossaryDefinition": "Payroll is a list of a company's employees and how much they are to be paid.",
          "toolExplanation": "Payroll tools help you pay your employees on time and accurately.",
          "Synonym": "Paying employees",
          "Synonym__1": "HR",
          "Synonym__2": "Employee compensation",
          "Synonym__3": "benefits",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Project management",
          "glossaryDefinition": "Project management is the practice of planning the project, defining the boundaries of what goals and activities the project will (and won't) involve, and supporting the broader team to ensure project goals are met in a specific timeframe",
          "toolExplanation": "Project management tools that help co-ops manage project timelines, share documents, track tasks, discuss issues, and more.",
          "Synonym": "Project planning",
          "Synonym__1": "Managing timelines",
          "Synonym__2": "Timeline",
          "Synonym__3": "Deliverables",
          "Synonym__4": "Management",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Shared calendar",
          "glossaryDefinition": null,
          "toolExplanation": "Calendar tools provide an online calendar software.",
          "Synonym": "Timetable",
          "Synonym__1": "Schedule",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Staffing",
          "glossaryDefinition": null,
          "toolExplanation": "Staffing tools help you or your customers schedule an appointment or service.",
          "Synonym": "Making appointments",
          "Synonym__1": "Appointments",
          "Synonym__2": "Booking",
          "Synonym__3": "Shift management",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Technology-building",
          "glossaryDefinition": "",
          "toolExplanation": "Technology-building tools give you the means to design and build digital tools.",
          "Synonym": "Tech",
          "Synonym__1": "Website",
          "Synonym__2": "Website builder",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Time management",
          "glossaryDefinition": "Time management is the process of managing your time in a way that is most effective to achieve your goals.",
          "toolExplanation": "Time management tools help you better manage you and your team's time.",
          "Synonym": "Schedule",
          "Synonym__1": "",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Time tracking",
          "glossaryDefinition": null,
          "toolExplanation": "Time tracking tools help you keep a record of the time you're spending on a task.",
          "Synonym": "Timesheet",
          "Synonym__1": "Signing in and out",
          "Synonym__2": "Clocking in and out",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Video conference",
          "glossaryDefinition": null,
          "toolExplanation": "Video conferencing tools help you talk to people through audio and video online.",
          "Synonym": "Video chat",
          "Synonym__1": "Video call",
          "Synonym__2": "Meetings",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        },
        {
          "category": "Tool",
          "term": "Website builder",
          "glossaryDefinition": null,
          "toolExplanation": "Website builders are tools that let you build a website easily and without knowing how to code.",
          "Synonym": "Website template",
          "Synonym__1": "Ecommerce",
          "Synonym__2": "",
          "Synonym__3": "",
          "Synonym__4": "",
          "Synonym__5": "",
          "Synonym__6": "",
          "Synonym__7": "",
          "Synonym__8": "",
          "": "",
          "__1": ""
        }
      ]

  let glossary = glossaryRaw.map(processGlossary).sort(function(a,b) {    
    return sortByObjectKey(a, b, "term");
  }); 

	if (glossary !== []) {
		res.setHeader('Content-Type', 'application/json');
		res.end(JSON.stringify(glossary));
	} else {
		next();
	}
}